-- Generato da tools/tendine.cjs --scrivi: NON modificare a mano.
-- Le voci delle tendine che scrivono dati, lette dal codice delle app.
-- Si applica al database dopo ogni --scrivi (lo usa s_controllo_tendine()).
begin;
delete from public.s_tendine_registro;
insert into public.s_tendine_registro (id, app, dove, tabella, colonna, voci) values
  ('gest.f-tipo', 'gestionale', 'index.html f-tipo', 'visite', 'tipo_accesso', array['5', '1', '2', '3', '4', '6', '7', '8', '9', '10', '11', '12']::text[]),
  ('gest.f-ppre-titolo', 'gestionale', 'index.html f-ppre-titolo', 'visite', 'ppre_titolo', array['Sig.', 'Sig.ra', 'Dott.', 'Dott.ssa', 'Geom.', 'P.I.', 'Ing.', 'Arch.', 'Avv.', 'Prof.']::text[]),
  ('gest.f-qual-ppre', 'gestionale', 'index.html f-qual-ppre', 'visite', 'qual_ppre', array['Addetto alla documentazione', 'Autonomo', 'Capo cantiere', 'Collaboratore esterno', 'Committente', 'Coordinatore', 'Dipendente', 'Dipendente ditta affidataria', 'Dipendente ditta in subappalto', 'Direttore tecnico di cantiere', 'Direttore tecnico impresa', 'Geometra di cantiere', 'Impiegato tecnico', 'Lavoratore', 'Lavoratore autonomo', 'Operaio', 'Operaio del committente', 'Preposto', 'Responsabile del Modello di Organizzazione e Gestione', 'Responsabile di cantiere', 'RLS', 'RSGSL', 'RSPP', 'RSPP aziendale', 'Socio dipendente', 'Socio titolare', 'Subappaltatore', 'Tecnico', 'Tecnico di cantiere', 'Tecnico impresa', 'Tecnico incaricato dal committente', 'Titolare', 'Tutor aziendale', 'Altro']::text[]),
  ('gest.f-comm-titolo', 'gestionale', 'index.html f-comm-titolo', 'visite', 'comm_titolo', array['Sig.', 'Sig.ra', 'Dott.', 'Dott.ssa', 'Geom.', 'P.I.', 'Ing.', 'Arch.', 'Avv.', 'Prof.']::text[]),
  ('gest.f-rl-titolo', 'gestionale', 'index.html f-rl-titolo', 'visite', 'rl_titolo', array['Sig.', 'Sig.ra', 'Dott.', 'Dott.ssa', 'Geom.', 'P.I.', 'Ing.', 'Arch.', 'Avv.']::text[]),
  ('gest.f-csp-titolo', 'gestionale', 'index.html f-csp-titolo', 'visite', 'csp_titolo', array['Sig.', 'Sig.ra', 'Dott.', 'Dott.ssa', 'Geom.', 'P.I.', 'Ing.', 'Arch.', 'Avv.']::text[]),
  ('gest.f-cse-titolo', 'gestionale', 'index.html f-cse-titolo', 'visite', 'cse_titolo', array['Sig.', 'Sig.ra', 'Dott.', 'Dott.ssa', 'Geom.', 'P.I.', 'Ing.', 'Arch.', 'Avv.']::text[]),
  ('gest.f-importo', 'gestionale', 'index.html f-importo', 'cantieri', 'cantiere_importo', array['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11']::text[]),
  ('gest.mc-importo', 'gestionale', 'index.html mc-importo', 'cantieri', 'cantiere_importo', array['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11']::text[]),
  ('gest.mc-tip-int', 'gestionale', 'index.html mc-tip-int', 'cantieri', 'cantiere_tip_int', array['1', '2', '3', '4']::text[]),
  ('gest.mc-tip-ope', 'gestionale', 'index.html mc-tip-ope', 'cantieri', 'cantiere_tip_ope', array['2', '1', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']::text[]),
  ('gest.mc-durata', 'gestionale', 'index.html mc-durata', 'cantieri', 'cantiere_durata', array['1', '2', '3', '4', '5', '6', '7']::text[]),
  ('gest.mp-titolo', 'gestionale', 'index.html mp-titolo', 'persone', 'titolo', array['Sig.', 'Sig.ra', 'Dott.', 'Dott.ssa', 'Geom.', 'P.I.', 'Ing.', 'Arch.', 'Avv.', 'Prof.', 'Rag.']::text[]),
  ('gest.mp-sesso', 'gestionale', 'index.html mp-sesso', 'persone', 'sesso', array['M', 'F']::text[]),
  ('gest.mi-forma', 'gestionale', 'index.html mi-forma', 'imprese', 'tipo_impresa', array['S.r.l.', 'S.r.l.s', 'S.r.l. Unipersonale', 'S.n.c.', 'S.A.S.', 'S.p.A.', 'S.coop.', 'Consorzio', 'Ditta Individuale', 'Lavoratore autonomo', 'Altro']::text[]),
  ('gest.mi-tipo-ccia', 'gestionale', 'index.html mi-tipo-ccia', 'imprese', 'tipo_iscrizione_ccia', array['Industriale', 'Artigiana', 'Cooperativa', 'Commerciale', 'Lavoratore autonomo', 'Altro']::text[]),
  ('gest.ei-tipo-ccia', 'gestionale', 'index.html ei-tipo-ccia', 'imprese', 'tipo_iscrizione_ccia', array['Industriale', 'Artigiana', 'Cooperativa', 'Commerciale', 'Lavoratore autonomo', 'Altro']::text[]),
  ('gest.mi-ccnl', 'gestionale', 'index.html mi-ccnl', 'imprese', 'contratto_ccnl', array['Edilizia Industria', 'Edilizia Artigianato', 'Edilizia Piccola industria', 'Edilizia Cooperative', 'Metalmeccanico Industria', 'Metalmeccanico Artigianato', 'Installatori Impianti', 'Legno', 'Altro']::text[]),
  ('gest.ei-ccnl', 'gestionale', 'index.html ei-ccnl', 'imprese', 'contratto_ccnl', array['Edilizia Industria', 'Edilizia Artigianato', 'Edilizia Piccola industria', 'Edilizia Cooperative', 'Metalmeccanico Industria', 'Metalmeccanico Artigianato', 'Installatori Impianti', 'Legno', 'Altro']::text[]),
  ('gest.mi-ceiv', 'gestionale', 'index.html mi-ceiv', 'imprese', 'cassa_edile', array['C.E.I.V.', 'EDILCASSA VENETO', 'CASSA EDILE BELLUNO', 'CASSA EDILE VENEZIA', 'CASSA EDILE VICENZA', 'ALTRO']::text[]),
  ('gest.ei-ceiv', 'gestionale', 'index.html ei-ceiv', 'imprese', 'cassa_edile', array['C.E.I.V.', 'EDILCASSA VENETO', 'CASSA EDILE BELLUNO', 'CASSA EDILE VENEZIA', 'CASSA EDILE VICENZA', 'ALTRO']::text[]),
  ('gest.ec-sogg', 'gestionale', 'index.html ec-sogg', 'committenti', 'tipo_sogg', array['PF', 'PG']::text[]),
  ('gest.ec-tipo', 'gestionale', 'index.html ec-tipo', 'committenti', 'committente_tipo', array['1', '2', '3']::text[]),
  ('gest.im-tipo-${idx}', 'gestionale', 'app-data.js TIPO_IMP_OPT', 'visite_imprese_presenti', 'tipo_imp', array['1', '2', '3', '4', '5', '6']::text[]),
  ('gest.avv-prio', 'gestionale', 'index.html avv-prio', 'avvisi', 'priorita', array['info', 'importante', 'urgente']::text[]),
  ('gest.cmp-pos', 'gestionale', 'index.html cmp-pos', 'campagne', 'posizione', array['verbale', 'email', 'entrambi']::text[]),
  ('segr.corsi.RUOLI_AZ', 'segreteria', 'js/corsi.js RUOLI_AZ', 's_corsi_iscritti', 'ruolo', array['DIPENDENTE', 'TITOLARE', 'SOCIO', 'PREPOSTO', 'RLS', 'RSPP', 'DATORE DI LAVORO', 'COLLABORATORE', 'ALTRO']::text[]),
  ('segr.corsi.QUALITA', 'segreteria', 'js/corsi.js QUALITA', 's_corsi_interventi', 'qualita', array['docente', 'codocente', 'relatore', 'ospite', 'moderatore', 'uditore']::text[]),
  ('segr.lookups.UFFICI', 'segreteria', 'js/lookups.js UFFICI', 's_protocollo', 'ufficio', array['Segreteria Area Sicurezza e Salute', 'Segreteria', 'Direzione', 'Presidenza', 'Amministrazione', 'Ufficio Formazione Continua', 'Consiglio']::text[]),
  ('segr.lookups.MEZZI', 'segreteria', 'js/lookups.js MEZZI', 's_protocollo', 'mezzo', array['e-mail', 'PEC', 'Consegna a mano', 'Lettera', 'Raccomandata', 'Pony Express', 'Fax', 'Altro']::text[]),
  ('segr.imprese.tipo_impresa', 'segreteria', 'js/imprese.js OPZIONI.tipo_impresa', 'imprese', 'tipo_impresa', array['S.r.l.', 'S.r.l.s', 'S.r.l. Unipersonale', 'S.n.c.', 'S.A.S.', 'S.p.A.', 'S.coop.', 'Consorzio', 'Ditta Individuale', 'Lavoratore autonomo', 'Altro']::text[]),
  ('segr.imprese.ruolo', 'segreteria', 'js/imprese.js OPZIONI.ruolo', 'imprese', 'ruolo', array['IMPRESA Edile', 'IMPRESA NON EDILE', 'IMPRESA IMPIANTI', 'LAVORATORE AUTONOMO', 'CONSORZIO', 'ENTE', 'STUDIO', 'LIBERO PROFESSIONISTA', 'CONSULENTE DEL LAVORO', 'FORNITORE', 'COMMITTENTE PERS. GIU.', 'COMMITTENTE PERS. FIS. Privato', 'COMMITTENTE PERS. FIS. Pubblico', 'SINDACATO', 'STAMPA', 'MEDICO', 'SPISAL', 'IMPRENDITORE', 'DIPENDENTE', 'SCUOLA EDILE CPT Padova', 'Studente SCUOLA EDILE CPT Padova']::text[]),
  ('segr.imprese.tipologia_impresa', 'segreteria', 'js/imprese.js OPZIONI.tipologia_impresa', 'imprese', 'tipologia_impresa', array['Industriale', 'Artigiana', 'Cooperativa', 'Commerciale', 'Lavoratore autonomo']::text[]),
  ('segr.imprese.tipo_iscrizione_ccia', 'segreteria', 'js/imprese.js OPZIONI.tipo_iscrizione_ccia', 'imprese', 'tipo_iscrizione_ccia', array['Industriale', 'Artigiana', 'Cooperativa', 'Commerciale', 'Lavoratore autonomo', 'Altro']::text[]),
  ('segr.imprese.contratto_ccnl', 'segreteria', 'js/imprese.js OPZIONI.contratto_ccnl', 'imprese', 'contratto_ccnl', array['Edilizia Industria', 'Edilizia Artigianato', 'Edilizia Piccola industria', 'Edilizia Cooperative', 'Metalmeccanico Industria', 'Metalmeccanico Artigianato', 'Installatori Impianti', 'Legno', 'Altro']::text[]),
  ('segr.imprese.ccnl', 'segreteria', 'js/imprese.js OPZIONI.ccnl', 'imprese', 'ccnl', array['Edilizia Industria', 'Edilizia Artigianato', 'Edilizia Piccola industria', 'Edilizia Cooperative', 'Metalmeccanico Industria', 'Metalmeccanico Artigianato', 'Installatori Impianti', 'Legno', 'Altro']::text[]),
  ('segr.imprese.cassa_edile', 'segreteria', 'js/imprese.js OPZIONI.cassa_edile', 'imprese', 'cassa_edile', array['C.E.I.V.', 'EDILCASSA VENETO', 'CASSA EDILE BELLUNO', 'CASSA EDILE VENEZIA', 'CASSA EDILE VICENZA', 'ALTRO']::text[]),
  ('segr.imprese.stato_cassa', 'segreteria', 'js/imprese.js OPZIONI.stato_cassa', 'imprese', 'stato_cassa', array['Attiva', 'Sospesa', 'Cessata', 'Non iscritta']::text[]),
  ('segr.imprese.rspp', 'segreteria', 'js/imprese.js OPZIONI.rspp', 'imprese', 'rspp', array['il responsabile del servizio di prevenzione e protezione è il datore di lavoro', 'il responsabile del servizio di prevenzione e protezione è un dipendente dell''impresa', 'il responsabile del servizio di prevenzione e protezione è un soggetto esterno all''impresa']::text[]),
  ('segr.visite.STATI', 'segreteria', 'js/visite.js STATI', 's_visite_richieste', 'stato', array['ricevuta', 'autorizzata', 'assegnata', 'in_corso', 'eseguita', 'chiusa', 'scartata']::text[]),
  ('segr.segnalazioni.STATI', 'segreteria', 'js/segnalazioni.js STATI', 's_segnalazioni', 'stato', array['ricevuta', 'istruita', 'autorizzata', 'assegnata', 'eseguita', 'riscontrata', 'chiusa', 'scartata']::text[]),
  ('segr.notifiche.STATI', 'segreteria', 'js/notifiche.js STATI', 's_notifiche_cantiere', 'stato', array['ricevuta', 'programmata', 'visitata', 'chiusa', 'scartata']::text[]),
  ('segr.conferenze.STATI', 'segreteria', 'js/conferenze.js STATI', 's_conferenze_cantiere', 'stato', array['ricevuta', 'autorizzata', 'programmata', 'svolta', 'chiusa', 'scartata']::text[]),
  ('segr.consulenze.STATI', 'segreteria', 'js/consulenze.js STATI', 's_consulenze', 'stato', array['ricevuta', 'girata', 'risposta_pronta', 'autorizzata', 'eseguita', 'chiusa', 'scartata']::text[]);
commit;
